# SPDX-FileCopyrightText: 2016-2018 CERN.
# SPDX-FileCopyrightText: 2026 Graz University of Technology.
# SPDX-License-Identifier: MIT

"""Add index on jobs_run job_id."""

from alembic import op

# revision identifiers, used by Alembic.
revision = "1784553083"
down_revision = "1764848648"
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_jobs_run_job_id",
        "jobs_run",
        ["job_id", "created"],
        if_not_exists=True,
    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_jobs_run_job_id",
        table_name="jobs_run",
    )
    # ### end Alembic commands ###
